"""8/10/16-bit integer bit-depth parity tests.

For every filter that accepts more than one integer bit depth, run it on the same
content at each depth, normalize the output to [0,1] by the format peak, and
assert the results match within the precision of the lower depth. This surfaces
bit-depth-specific bugs (a hard-coded 255 peak, overflow at 16-bit, scaling that
only holds at one depth, ...).

Not covered: single-int-depth filters (Checkmate, CombMask, CombMaskMT, ColorMap,
AdaptiveBinarize). PackRGB is excluded -- its output is a depth-specific bit
packing (8+8+8 vs 10+10+10 into one Gray32), so cross-depth values are not
comparable. CLAHE is excluded too (histogram equalisation is depth-resolution
dependent by design; see its section below).
"""

import pytest
import vapoursynth as vs

from helpers import max_abs_diff, props


def peak(bits: int) -> int:
    return (1 << bits) - 1


# (bits, format) sets per colour family. Use the subset a filter actually accepts.
GRAY = [(8, vs.GRAY8), (10, vs.GRAY10), (16, vs.GRAY16)]
YUV420 = [(8, vs.YUV420P8), (10, vs.YUV420P10), (16, vs.YUV420P16)]
YUV444 = [(8, vs.YUV444P8), (10, vs.YUV444P10), (16, vs.YUV444P16)]
RGB = [(8, vs.RGB24), (10, vs.RGB30), (16, vs.RGB48)]


def normalize(clip: vs.VideoNode, bits: int) -> vs.VideoNode:
    """Integer clip -> f32 in [0,1] (divide every plane by the format peak).
    Lets outputs at different bit depths be compared on a common scale."""
    out = clip.format.replace(sample_type=vs.FLOAT, bits_per_sample=32).id
    return clip.std.Expr(f"x {peak(bits)} /", format=out)


def assert_pixel_parity(results, *, lsb: float = 4.0, n: int = 0) -> None:
    """results: list of (bits, clip). Normalize each output to [0,1] and compare
    every lower-depth result to the highest-depth one. Tolerance is `lsb` LSBs of
    the *lower* depth (its inherent quantization), so a correct filter passes and
    a scaling/overflow bug (diff far larger than a few LSB) fails."""
    results = sorted(results, key=lambda r: -r[0])
    hi_bits, hi_clip = results[0]
    refn = normalize(hi_clip, hi_bits)
    for bits, clip in results[1:]:
        cn = normalize(clip, bits)
        tol = lsb / peak(bits)
        for p in range(refn.format.num_planes):
            d = max_abs_diff(refn, cn, plane=p, n=n)
            assert d <= tol, f"{bits}-bit vs {hi_bits}-bit, plane {p}: max|Δnorm| = {d} > {tol} ({lsb} LSB)"


def assert_prop_parity(results, keys, *, tol: float, n: int = 0) -> None:
    """results: list of (bits, clip). Compare frame-prop values across depths.
    Only valid for depth-independent props (already normalized, or a dB/score);
    for raw per-depth props normalize with peak(bits) in the test instead."""
    results = sorted(results, key=lambda r: -r[0])
    hi_bits, hi_clip = results[0]
    ref = props(hi_clip, n)
    for bits, clip in results[1:]:
        cur = props(clip, n)
        for k in keys:
            assert abs(ref[k] - cur[k]) <= tol, f"{k}: {bits}-bit={cur[k]} {hi_bits}-bit={ref[k]} (tol {tol})"


# ===========================================================================
# Per-filter parity tests (generated by the int-parity workflow) below.
# ===========================================================================


# --- Bilateral ---------------------------------------------------------------
# Args are depth-independent: sigmaS is in pixels, and sigmaR is a 0..1 fraction
# (the range LUT divides the raw intensity diff by peak=getHistLen-1 before the
# Gaussian, src/filters/bilateral.zig gaussianFunctionRangeLUTGeneration). Peak is
# derived per depth from getHistLen, not hard-coded, so the same args go to every
# depth and normalized outputs must match. A hard-coded/wrong peak or 16-bit
# overflow would break that and fail here.
_BILATERAL_FAMILIES = [
    ("gray", GRAY),
    ("yuv420", YUV420),
    ("rgb", RGB),
]
_BILATERAL_ARGS = [
    ("smooth", dict(sigmaS=2, sigmaR=2)),
    ("sharp_range", dict(sigmaS=2, sigmaR=0.02)),
]


@pytest.mark.parametrize("family", [f for _, f in _BILATERAL_FAMILIES], ids=[n for n, _ in _BILATERAL_FAMILIES])
@pytest.mark.parametrize("args", [a for _, a in _BILATERAL_ARGS], ids=[n for n, _ in _BILATERAL_ARGS])
def test_int_parity_bilateral(make_clip, family, args):
    results = [(bits, make_clip(fmt).vszip.Bilateral(**args)) for bits, fmt in family]
    assert_pixel_parity(results)


# --- BoxBlur -----------------------------------------------------------------
# The integer kernel uses a fixed-point reciprocal (inv = (1<<32 + radius)/ksize)
# that depends ONLY on radius/ksize, never on the bit depth, and accumulates in
# u64; output is a normalized average in the input's value range. radius/passes
# are depth-independent. Two arg sets exercise both dispatch paths: comptime
# (hradius == vradius <= 22, single pass) and runtime (asymmetric + multi-pass).
_BOXBLUR_ARGS = {
    "comptime": dict(hradius=3, vradius=3),
    "runtime": dict(hradius=6, vradius=3, hpasses=2, vpasses=2),
}


@pytest.mark.parametrize("family", [GRAY, YUV420, RGB], ids=["gray", "yuv420", "rgb"])
@pytest.mark.parametrize("path", list(_BOXBLUR_ARGS), ids=list(_BOXBLUR_ARGS))
def test_int_parity_boxblur(make_clip, family, path):
    args = _BOXBLUR_ARGS[path]
    results = [(bits, make_clip(fmt).vszip.BoxBlur(**args)) for bits, fmt in family]
    assert_pixel_parity(results)


# --- Limiter -----------------------------------------------------------------
def _scaled_band(bits, num_planes):
    # int min/max are RAW pixel values (validated vs peak=(1<<bits)-1 in
    # limiterCreate, applied with no internal scaling). Scale per depth so the
    # SAME normalized band [0.1, 0.8] is clamped at every depth.
    mn = round(0.1 * peak(bits))
    mx = round(0.8 * peak(bits))
    return dict(min=[mn] * num_planes, max=[mx] * num_planes)


@pytest.mark.parametrize("family", [GRAY, YUV420, RGB], ids=["gray", "yuv420", "rgb"])
def test_int_parity_limiter_minmax(make_clip, family):
    # Explicit per-plane min/max: RAW pixel values scaled per depth so the same
    # normalized window is clamped everywhere. A hard-coded 8-bit peak or missing
    # per-depth scaling makes the 10/16-bit clamp band wrong and diverge.
    results = []
    for bits, fmt in family:
        num_planes = make_clip(fmt).format.num_planes
        out = make_clip(fmt).vszip.Limiter(**_scaled_band(bits, num_planes))
        results.append((bits, out))
    assert_pixel_parity(results)


@pytest.mark.parametrize("family", [GRAY, YUV420, RGB], ids=["gray", "yuv420", "rgb"])
def test_int_parity_limiter_tv_range_default(make_clip, family):
    # Default path (no min/max) with tv_range=True: selects the per-depth comptime
    # range tables ([16<<(b-8), 235<<(b-8)] etc.), which are depth-scaled, so the
    # same flag must clamp the same normalized band; a wrong table fails parity.
    results = [(bits, make_clip(fmt).vszip.Limiter(tv_range=True)) for bits, fmt in family]
    assert_pixel_parity(results)


# --- LimitFilter -------------------------------------------------------------
# dark_thr/bright_thr are on the 8-bit full-data-range scale and scaled to the
# clip depth by value_range/255 (mvsfunc semantics), so the same value gives the
# SAME normalized threshold at every depth. LimitFilter's soft-limit amplifies
# input quantization near the transition, so -- like Deband -- build the content
# once at the family's lowest depth and Point-upscale it (identical normalized
# content) to isolate the filter's depth handling from input quantization.
def _lf_results(make_clip, family, *, ref=False, **args):
    _, base_fmt = min(family, key=lambda bf: bf[0])
    base = make_clip(base_fmt)
    results = []
    for bits, fmt in family:
        src = base if fmt == base_fmt else base.resize.Point(format=fmt)
        flt = src.vszip.BoxBlur(hradius=2, vradius=2)
        r = src.vszip.BoxBlur(hradius=4, vradius=4) if ref else None
        results.append((bits, flt.vszip.LimitFilter(src, r, **args)))
    return results


@pytest.mark.parametrize("dark,bright,elast", [(4, 4, 2), (16, 2, 4), (8, 16, 1.5)])
def test_int_parity_limitfilter_gray(make_clip, dark, bright, elast):
    results = _lf_results(make_clip, GRAY, dark_thr=dark, bright_thr=bright, elast=elast)
    assert_pixel_parity(results)


@pytest.mark.parametrize("dark,bright,elast", [(4, 4, 2), (16, 2, 4), (8, 16, 1.5)])
def test_int_parity_limitfilter_yuv420(make_clip, dark, bright, elast):
    results = _lf_results(make_clip, YUV420, dark_thr=dark, bright_thr=bright, elast=elast)
    assert_pixel_parity(results)


def test_int_parity_limitfilter_yuv420_per_plane(make_clip):
    # per-plane luma/chroma argument arrays; same 8-bit values at every depth.
    results = _lf_results(make_clip, YUV420, dark_thr=[16, 4], bright_thr=[16, 4], elast=[4, 2])
    assert_pixel_parity(results)


@pytest.mark.parametrize("fmt_family", [GRAY, YUV420], ids=["gray", "yuv420"])
def test_int_parity_limitfilter_ref(make_clip, fmt_family):
    # ref-clip variant (refb=true path). With a distinct ref clip the soft-limit
    # amplifies the tiny per-depth BoxBlur differences in BOTH flt and ref near the
    # transition, so even on identical content the cross-depth divergence is larger
    # (~10 LSB) -- inherent to the soft-limit, not a scaling bug, hence a looser
    # bound. A real depth-scaling bug would still diverge by orders of magnitude.
    results = _lf_results(make_clip, fmt_family, ref=True, dark_thr=8, bright_thr=8, elast=3)
    assert_pixel_parity(results, lsb=14.0)


# --- Deband ------------------------------------------------------------------
DEBAND_FAMILIES = {"gray": GRAY, "yuv420": YUV420}


def _deband_parity_results(make_clip, family, args):
    """Build ONE base clip at the family's lowest (8-bit) format, then expand it
    UP to each higher depth with Point (exact peak scaling) so the normalized
    content is identical at every depth. Deband independently resized to each
    depth would feed different content (a 257-step staircase vs a smooth 16-bit
    gradient debands differently), which is incomparable -- not a bug. thr/grain
    are 8-bit-normalized args scaled to 16-bit internally, so pass them unchanged
    at every depth. grain=0 + fixed seed makes the output deterministic."""
    _, base_fmt = min(family, key=lambda bf: bf[0])
    base = make_clip(base_fmt)
    results = []
    for bits, fmt in family:
        src = base if fmt == base_fmt else base.resize.Point(format=fmt)
        results.append((bits, src.vszip.Deband(**args)))
    return results


@pytest.mark.parametrize("family_name", ["gray", "yuv420"])
@pytest.mark.parametrize(("sample_mode", "blur_first"), [(1, True), (2, True), (2, False), (5, True), (7, True)])
def test_int_parity_deband(make_clip, family_name, sample_mode, blur_first):
    family = DEBAND_FAMILIES[family_name]
    args = dict(thr=48, grain=0, seed=7, sample_mode=sample_mode, blur_first=blur_first)
    results = _deband_parity_results(make_clip, family, args)
    # grain=0 -> deterministic; lower depths differ only by the dither-back
    # quantization (~1.6 LSB at 8-bit), so the default 4-LSB tolerance holds.
    assert_pixel_parity(results, lsb=4.0)


# --- CLAHE -------------------------------------------------------------------
# CLAHE is deliberately NOT in the depth-parity sweep: it is histogram
# equalisation with hist_size = 2^depth bins, so the equalisation *resolution*
# scales with bit depth (256 vs 65536 bins) -- this matches OpenCV, which also
# uses 65536 bins for 16-bit. Its `limit` is a per-bin clip count, so it is
# depth-relative: the wiki says to reproduce the 8-bit result at 16-bit you must
# multiply `limit` by 256. Even with that scaling the finer 16-bit histogram
# yields a different (not buggy) result -- measured 8-vs-16 divergence ranges
# 0.02..0.22 normalized depending on limit/tiles, so a meaningful parity bound
# does not exist. vszip's 8-bit CLAHE matches OpenCV to < 0.01, so there is no
# bit-depth bug to surface here. (CLAHE's own behaviour is locked by its golden
# tests; a separate non-divisible-dims OOB lives in test_known_bugs.py.)


# --- PlaneAverage ------------------------------------------------------------
# psmAvg (and psmDiff in clipb mode) are NORMALIZED to [0,1]: the int kernel
# divides the accumulator by peak=(1<<bits)-1 per depth (planeaverage.zig
# result()/averageRef()), so the props are depth-independent and comparable
# directly. exclude= is REQUIRED and a RAW pixel value (kernel does `v == e`), so
# it is scaled per depth (round(frac*peak)) to exclude the SAME fractional pixels
# at every depth. Single-plane keeps psmAvg scalar; multi-plane returns a list.
_PA_FAMILIES = {
    "gray": (GRAY, [0]),
    "yuv420": (YUV420, [0, 1, 2]),
    "rgb": (RGB, [0, 1, 2]),
}
_PA_LSB = 2.0  # LSB of the lower depth; observed cross-depth noise is < 0.35 LSB


def _pa_exclude(bits, fracs):
    """Raw per-depth pixel values for the same fractional intensities."""
    return [round(fr * peak(bits)) for fr in fracs]


def _pa_assert(results, key):
    """Compare a normalized prop (scalar or per-plane list) across depths."""
    results = sorted(results, key=lambda r: -r[0])
    hi_bits, hi_p = results[0]
    ref = hi_p[key] if isinstance(hi_p[key], list) else [hi_p[key]]
    for bits, p in results[1:]:
        cur = p[key] if isinstance(p[key], list) else [p[key]]
        assert len(cur) == len(ref), f"{key}: plane count {len(cur)} != {len(ref)}"
        tol = _PA_LSB / peak(bits)
        for i, (a, b) in enumerate(zip(cur, ref)):
            assert abs(a - b) <= tol, (
                f"{key}[{i}]: {bits}-bit={a} {hi_bits}-bit={b} |delta|={abs(a - b)} > {tol} ({_PA_LSB} LSB)"
            )


@pytest.mark.parametrize("family", ["gray", "yuv420", "rgb"])
def test_int_parity_planeaverage_avg(make_clip, family):
    """psmAvg parity across 8/10/16, with an active exclude scaled per depth."""
    fmts, planes = _PA_FAMILIES[family]
    results = [
        (bits, props(make_clip(fmt).vszip.PlaneAverage(exclude=_pa_exclude(bits, [0.5, 0.7]), planes=planes)))
        for bits, fmt in fmts
    ]
    _pa_assert(results, "psmAvg")


@pytest.mark.parametrize("family", ["gray", "yuv420", "rgb"])
def test_int_parity_planeaverage_diff(make_clip, family):
    """clipb diff mode: psmDiff (and psmAvg) parity across 8/10/16. The distorted
    clipb is a real BoxBlur of the source; psmDiff is normalized by peak per depth.
    exclude is a never-matching sentinel so the diff path runs without exclusions."""
    fmts, planes = _PA_FAMILIES[family]
    results = []
    for bits, fmt in fmts:
        src = make_clip(fmt)
        dist = src.std.BoxBlur(hradius=2, vradius=2)
        results.append((bits, props(src.vszip.PlaneAverage(exclude=[-1], clipb=dist, planes=planes))))
    _pa_assert(results, "psmAvg")
    _pa_assert(results, "psmDiff")


# --- PlaneMinMax -------------------------------------------------------------
# psmMin/psmMax are stored RAW per depth for int (kernel: props.setInt(retval));
# psmDiff is stored NORMALIZED (diffacc/total/peak, a 0..1 fraction). minthr/maxthr
# are 0..1 fractions of the pixel count -> depth-independent. So Min/Max are
# normalized by peak(bits) by hand before comparing; Diff is already scale-free.
_PMM_FAMILIES = [
    ("gray", GRAY, [0]),
    ("yuv420", YUV420, [0, 1, 2]),
    ("rgb", RGB, [0, 1, 2]),
]


def _pmm_norm_minmax(p, bits):
    """Normalize RAW per-depth psmMin/psmMax to [0,1]; always return lists."""
    mn, mx = p["psmMin"], p["psmMax"]
    mn = list(mn) if isinstance(mn, (list, tuple)) else [mn]
    mx = list(mx) if isinstance(mx, (list, tuple)) else [mx]
    pk = peak(bits)
    return [v / pk for v in mn], [v / pk for v in mx]


@pytest.mark.parametrize("name,family,planes", _PMM_FAMILIES, ids=[f[0] for f in _PMM_FAMILIES])
def test_int_parity_planeminmax_minmax(make_clip, name, family, planes):
    """psmMin/psmMax parity: the same threshold fraction must select the same
    physical value at every depth once normalized by the depth's peak."""
    args = dict(minthr=0.1, maxthr=0.1, planes=planes)
    norm = [(bits, *_pmm_norm_minmax(props(make_clip(fmt).vszip.PlaneMinMax(**args)), bits)) for bits, fmt in family]
    norm.sort(key=lambda r: -r[0])
    hi_bits, hi_min, hi_max = norm[0]
    for bits, nmin, nmax in norm[1:]:
        tol = 4.0 / peak(bits)  # histogram thresholding can land on an adjacent value across depths (~1.1 LSB)
        for pi, (a, b) in enumerate(zip(hi_min, nmin)):
            assert abs(a - b) <= tol, f"{name} Min plane {pi}: {bits}b={b} {hi_bits}b={a} |delta|={abs(a-b)} > {tol}"
        for pi, (a, b) in enumerate(zip(hi_max, nmax)):
            assert abs(a - b) <= tol, f"{name} Max plane {pi}: {bits}b={b} {hi_bits}b={a} |delta|={abs(a-b)} > {tol}"


@pytest.mark.parametrize("name,family,planes", _PMM_FAMILIES, ids=[f[0] for f in _PMM_FAMILIES])
def test_int_parity_planeminmax_diff(make_clip, name, family, planes):
    """psmDiff parity: the mean per-pixel abs difference vs a blurred reference is
    stored already peak-normalized (scale-free 0..1), so it must agree across depths."""
    results = []
    for bits, fmt in family:
        src = make_clip(fmt)
        ref = src.vszip.BoxBlur(hradius=1, vradius=1)
        out = src.vszip.PlaneMinMax(minthr=0.1, maxthr=0.1, clipb=ref, planes=planes)
        d = props(out)["psmDiff"]
        results.append((bits, list(d) if isinstance(d, (list, tuple)) else [d]))
    results.sort(key=lambda r: -r[0])
    hi_bits, hi = results[0]
    tol = 2e-3  # measured worst |delta| ~2.2e-4 (8-bit blur quantization); ~9x margin
    for bits, d in results[1:]:
        for pi, (a, b) in enumerate(zip(hi, d)):
            assert abs(a - b) <= tol, f"{name} Diff plane {pi}: {bits}b={b} {hi_bits}b={a} |delta|={abs(a-b)} > {tol}"


# --- SSIMULACRA2 -------------------------------------------------------------
# No scalar args; both inputs are funneled through toRGBS + linearize internally,
# the resize plugin normalizing each integer depth by its own peak, so the score
# is depth-independent by construction. Distorted is a real degradation built at
# each depth. Compare the scale-free "SSIMULACRA2" score directly.
DISTORTIONS_SSIM = {
    "blur1": dict(hradius=1, vradius=1),  # mild distortion (most sensitive to quantization)
    "blur3": dict(hradius=3, vradius=3),  # strong distortion
}


@pytest.mark.parametrize("family", [YUV420, YUV444], ids=["yuv420", "yuv444"])
@pytest.mark.parametrize("dist", list(DISTORTIONS_SSIM))
def test_int_parity_ssimulacra2(make_clip, family, dist):
    results = []
    for bits, fmt in family:
        ref = make_clip(fmt)
        distorted = ref.vszip.BoxBlur(**DISTORTIONS_SSIM[dist])
        results.append((bits, ref.vszip.SSIMULACRA2(distorted)))
    # tol=0.5 absolute: passes legitimate per-depth content quantization (worst
    # observed Δ ~0.16) but a wrong-peak bug shifts the score by tens of points.
    assert_prop_parity(results, ["SSIMULACRA2"], tol=0.5)


# --- XPSNR -------------------------------------------------------------------
# YUV-only, 8/10-bit only. The dB score is peak-normalized by construction
# (10*log10(w*h*(2^depth-1)^2 / wsse)), so the SAME relative distortion gives the
# SAME dB at 8 vs 10 bit, within quantization. A wrong/hard-coded peak would shift
# the dB by ~12 dB, far beyond the 0.15 dB tolerance (measured Δ <= 0.05 dB).
XPSNR_KEYS = ("XPSNR_Y", "XPSNR_U", "XPSNR_V")
XPSNR_PARITY_SUBSAMPLINGS = [
    ("420", [(8, vs.YUV420P8), (10, vs.YUV420P10)]),
    ("422", [(8, vs.YUV422P8), (10, vs.YUV422P10)]),
    ("444", [(8, vs.YUV444P8), (10, vs.YUV444P10)]),
]


@pytest.mark.parametrize("temporal", [True, False], ids=["temporal", "spatial"])
@pytest.mark.parametrize("family", [f for _, f in XPSNR_PARITY_SUBSAMPLINGS], ids=[s for s, _ in XPSNR_PARITY_SUBSAMPLINGS])
def test_int_parity_xpsnr(make_temporal_clip, family, temporal):
    # Build a finite, non-trivial distortion (BoxBlur) at each depth; ref==dist
    # would score +inf. temporal/verbose are not pixel-unit args.
    results = []
    for bits, fmt in family:
        ref = make_temporal_clip(fmt)
        dist = ref.vszip.BoxBlur(hradius=2, vradius=2)
        out = vs.core.vszip.XPSNR(ref, dist, temporal=temporal, verbose=False)
        results.append((bits, out))
    # temporal path carries inter-frame state; compare every frame in order.
    hi = results[0][1]
    for n in range(hi.num_frames):
        assert_prop_parity(results, XPSNR_KEYS, tol=0.15, n=n)
