"""f16 <-> f32 parity tests.

For every filter that accepts a half-float (f16) format, run it on f16 input and
on the *byte-identical* f32 input (the f16 data widened to f32), then assert the
two outputs match to within f16 output precision.

Using identical data in both containers isolates the filter's f16 code path from
input quantization: any difference beyond f16 output rounding means the f16 path
diverges from the f32 path.

Filters that reject f16 outright (Checkmate, CombMask(MT), CLAHE, ColorMap,
Deband, PackRGB, AdaptiveBinarize, XPSNR, SSIMULACRA2, ...) are covered by their
own validation tests.
"""

import pytest
import vapoursynth as vs

from helpers import max_abs_diff, props

# f16 format -> its matching f32 format
F16_TO_F32 = {
    vs.GRAYH: vs.GRAYS,
    vs.YUV420PH: vs.YUV420PS,
    vs.YUV422PH: vs.YUV422PS,
    vs.YUV444PH: vs.YUV444PS,
    vs.RGBH: vs.RGBS,
}


def pair(make, f16_fmt: int):
    """(f16 clip, f32 clip) carrying byte-identical data: build the f16 clip,
    then widen a copy to f32 (Point = format change only, no resampling) so any
    output difference is the filter's f16 path, not input quantization."""
    f16 = make(f16_fmt)
    f32 = f16.resize.Point(format=F16_TO_F32[f16_fmt])
    return f16, f32


def assert_pixel_parity(out_f16: vs.VideoNode, out_f32: vs.VideoNode, *, tol: float, n: int = 0) -> None:
    """Widen the f16 output to f32 and assert max|f16-f32| <= tol per plane."""
    widened = out_f16.resize.Point(format=out_f32.format.id)
    for p in range(out_f32.format.num_planes):
        d = max_abs_diff(widened, out_f32, plane=p, n=n)
        assert d <= tol, f"plane {p}: max|f16-f32| = {d} > {tol}"


def assert_prop_parity(out_f16: vs.VideoNode, out_f32: vs.VideoNode, keys, *, tol: float, n: int = 0) -> None:
    """Assert abs(prop_f16 - prop_f32) <= tol for each requested frame-prop key."""
    a, b = props(out_f16, n), props(out_f32, n)
    for k in keys:
        assert abs(a[k] - b[k]) <= tol, f"{k}: f16={a[k]} f32={b[k]} (tol {tol})"


# ===========================================================================
# Per-filter parity tests (generated by the f16-parity workflow) below.
# ===========================================================================


# --- Bilateral --------------------------------------------------------------


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.YUV420PH, vs.RGBH],
    ids=["GRAYH", "YUV420PH", "RGBH"],
)
def test_f16_parity_bilateral(make_clip, f16_fmt):
    # Single-clip bilateral with meaningful spatial/range sigmas so the kernel
    # does real edge-preserving work. The f16 and f32 inputs are byte-identical
    # (f32 widened from the f16 clip), so any output difference is the filter's
    # f16 float path -- including the auto-selected algorithm computing in f16
    # vs f32 precision.
    src16, src32 = pair(make_clip, f16_fmt)
    out16 = src16.vszip.Bilateral(sigmaS=2, sigmaR=2)
    out32 = src32.vszip.Bilateral(sigmaS=2, sigmaR=2)
    # tol ~= 1e-3 is about 2 ULP of f16 near 1.0 on the 0..1 float scale.
    assert_pixel_parity(out16, out32, tol=1e-3)


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.YUV420PH, vs.RGBH],
    ids=["GRAYH", "YUV420PH", "RGBH"],
)
def test_f16_parity_bilateral_small_sigmar(make_clip, f16_fmt):
    # A small sigmaR (0.02) pushes the auto-selector toward algorithm 2 and a
    # tight range LUT; the f16 range/weight accumulation is where divergence is
    # most likely to bite, so exercise it separately from the broad-sigma case.
    src16, src32 = pair(make_clip, f16_fmt)
    out16 = src16.vszip.Bilateral(sigmaS=2, sigmaR=0.02)
    out32 = src32.vszip.Bilateral(sigmaS=2, sigmaR=0.02)
    assert_pixel_parity(out16, out32, tol=1e-3)


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.YUV420PH, vs.RGBH],
    ids=["GRAYH", "YUV420PH", "RGBH"],
)
def test_f16_parity_bilateral_ref(make_clip, f16_fmt):
    # Joint (cross) bilateral: a separate ref clip drives the range weights.
    # Build the ref in f16 from the (f16) source and widen it to f32 so both
    # the source and the ref are byte-identical across the two runs.
    src16, src32 = pair(make_clip, f16_fmt)
    # std.BoxBlur has no f16 support; use vszip.BoxBlur (which does) and widen
    # the f16 ref to f32 so the ref is byte-identical across the two runs.
    ref16 = src16.vszip.BoxBlur(hradius=5, vradius=5)
    ref32 = ref16.resize.Point(format=F16_TO_F32[f16_fmt])
    out16 = src16.vszip.Bilateral(sigmaS=2, sigmaR=0.05, ref=ref16)
    out32 = src32.vszip.Bilateral(sigmaS=2, sigmaR=0.05, ref=ref32)
    assert_pixel_parity(out16, out32, tol=1e-3)


# --- BoxBlur ----------------------------------------------------------------


@pytest.mark.parametrize("f16_fmt", [vs.GRAYH, vs.YUV420PH, vs.RGBH])
def test_f16_parity_boxblur_comptime(make_clip, f16_fmt):
    # Symmetric radius 3, single pass, hradius==vradius<=22 -> BoxBlurCT path.
    # Both f16 and f32 share byte-identical input, so any divergence is the
    # filter's f16 accumulation, not input quantization.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.BoxBlur(hradius=3, vradius=3)
    out32 = f32.vszip.BoxBlur(hradius=3, vradius=3)
    # ~2 ULP of f16 near 1.0 on the 0..1 scale.
    assert_pixel_parity(out16, out32, tol=1e-3)


@pytest.mark.parametrize("f16_fmt", [vs.GRAYH, vs.YUV420PH, vs.RGBH])
def test_f16_parity_boxblur_runtime(make_clip, f16_fmt):
    # hradius != vradius and multi-pass forces the BoxBlurRT path
    # (use_rt = hradius!=vradius or hradius>22 or hpasses>1 or vpasses>1).
    # Multi-pass re-blurs an already-blurred plane, so the f16 rounding error
    # compounds; this is the case most likely to expose divergence.
    f16, f32 = pair(make_clip, f16_fmt)
    args = dict(hradius=6, vradius=3, hpasses=2, vpasses=2)
    out16 = f16.vszip.BoxBlur(**args)
    out32 = f32.vszip.BoxBlur(**args)
    # Same scale as the comptime case; if compounded f16 error pushes past 2 ULP
    # the assert should fire and expose it (we deliberately do NOT relax it).
    assert_pixel_parity(out16, out32, tol=1e-3)


@pytest.mark.parametrize("f16_fmt", [vs.GRAYH, vs.YUV420PH, vs.RGBH])
def test_f16_parity_boxblur_large_radius(make_clip, f16_fmt):
    # Large symmetric radius (>22) also takes the runtime path and sums many
    # samples into one f16 accumulator -- the widest exposure of f16 rounding.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.BoxBlur(hradius=30, vradius=30)
    out32 = f32.vszip.BoxBlur(hradius=30, vradius=30)
    assert_pixel_parity(out16, out32, tol=1e-3)


# --- Limiter ----------------------------------------------------------------


@pytest.mark.parametrize(
    ("f16_fmt", "lo", "hi"),
    [
        (vs.GRAYH, [0.1], [0.8]),
        (vs.YUV420PH, [0.1, 0.1, 0.1], [0.8, 0.8, 0.8]),
        (vs.RGBH, [0.1, 0.1, 0.1], [0.8, 0.8, 0.8]),
    ],
    ids=["grayh", "yuv420ph", "rgbh"],
)
def test_f16_parity_limiter(make_clip, f16_fmt, lo, hi):
    # Limiter's explicit-min/max path (LimiterRT) stores the bounds as f32 and,
    # for an f16 clip, casts them to f16 at the clamp: dst = min(max(lo, x), hi).
    # Input is byte-identical (f16 widened to f32 is exact), so any divergence
    # comes from (a) the f16 rounding of the clamp bounds and (b) the f16 output
    # quantization. With min=0.1/max=0.8 the bounds quantize to f16 and a band of
    # pixels gets clamped on both paths; near 0.1..0.8 f16 ULP is ~5e-4, so the
    # worst-case widen(f16)-vs-f32 mismatch at the clamp plateau and on pass-
    # through pixels is ~1 ULP. tol=1e-3 (~2 ULP) is the right f16-precision bar.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.Limiter(min=lo, max=hi)
    out32 = f32.vszip.Limiter(min=lo, max=hi)
    assert_pixel_parity(out16, out32, tol=1e-3)


def test_f16_parity_limiter_default_full_range(make_clip):
    # Comptime (no min/max) float path: default clamps each plane to the full
    # float range table (luma 0..1, chroma -0.5..0.5). Exercises filter.getFrame
    # with has_min=false, mask=false. Same f16-precision bar applies.
    f16, f32 = pair(make_clip, vs.YUV420PH)
    out16 = f16.vszip.Limiter()
    out32 = f32.vszip.Limiter()
    assert_pixel_parity(out16, out32, tol=1e-3)


def test_f16_parity_limiter_mask(make_clip):
    # mask=true forces the rgbf (0..1) range on every plane of a float YUV clip,
    # clamping negative chroma to 0. Distinct comptime branch (yuv=false). The
    # 0 floor and 1 ceil are exact in f16, so divergence is purely f16 output
    # quantization of pass-through pixels.
    f16, f32 = pair(make_clip, vs.YUV420PH)
    out16 = f16.vszip.Limiter(mask=True)
    out32 = f32.vszip.Limiter(mask=True)
    assert_pixel_parity(out16, out32, tol=1e-3)


# --- LimitFilter ------------------------------------------------------------


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.YUV420PH, vs.RGBH],
    ids=["GRAYH", "YUV420PH", "RGBH"],
)
def test_f16_parity_limitfilter(make_clip, f16_fmt):
    # Build a byte-identical (f16, f32) src pair, then build the flt input the
    # same way: blur the f16 src in f16, widen that blurred result to f32. So
    # both LimitFilter inputs (flt and src) are byte-identical across the two
    # runs and the ONLY thing that can diverge is LimitFilter's own f16 path
    # (it computes in f32 internally and @floatCasts the result back to f16).
    src16, src32 = pair(make_clip, f16_fmt)
    flt16 = src16.vszip.BoxBlur(hradius=2, vradius=2)
    flt32 = flt16.resize.Point(format=F16_TO_F32[f16_fmt])

    out16 = flt16.vszip.LimitFilter(src16, dark_thr=8, bright_thr=8, elast=3)
    out32 = flt32.vszip.LimitFilter(src32, dark_thr=8, bright_thr=8, elast=3)

    # Output is f16-precision: at most ~2 ULP of f16 near 1.0 on the 0..1 scale.
    assert_pixel_parity(out16, out32, tol=1e-3)


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.YUV420PH, vs.RGBH],
    ids=["GRAYH", "YUV420PH", "RGBH"],
)
def test_f16_parity_limitfilter_ref(make_clip, f16_fmt):
    # Same parity check but exercising the ref-clip code path (refb=true): the
    # diff/weight is computed from a distinct reference clip. ref is built in
    # f16 and widened to f32 so it too is byte-identical across the runs.
    src16, src32 = pair(make_clip, f16_fmt)
    flt16 = src16.vszip.BoxBlur(hradius=2, vradius=2)
    flt32 = flt16.resize.Point(format=F16_TO_F32[f16_fmt])
    ref16 = src16.vszip.BoxBlur(hradius=4, vradius=4)
    ref32 = ref16.resize.Point(format=F16_TO_F32[f16_fmt])

    out16 = flt16.vszip.LimitFilter(src16, ref16, dark_thr=8, bright_thr=8, elast=3)
    out32 = flt32.vszip.LimitFilter(src32, ref32, dark_thr=8, bright_thr=8, elast=3)

    assert_pixel_parity(out16, out32, tol=1e-3)


# --- PlaneMinMax ------------------------------------------------------------


@pytest.mark.parametrize("f16_fmt", [vs.GRAYH, vs.YUV420PH, vs.RGBH])
def test_f16_parity_planeminmax_nothr(make_clip, f16_fmt):
    # No-thr path: min/max are read directly off the float samples. With
    # byte-identical data (f16 widened to f32) the values must be EXACTLY equal.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.PlaneMinMax(planes=[0])
    out32 = f32.vszip.PlaneMinMax(planes=[0])
    assert_prop_parity(out16, out32, ["psmMin", "psmMax"], tol=0.0)


@pytest.mark.parametrize("f16_fmt", [vs.GRAYH, vs.YUV420PH, vs.RGBH])
def test_f16_parity_planeminmax_thr(make_clip, f16_fmt):
    # Threshold path quantises samples into a 65536-bin histogram via the index
    # `@as(f32, v) * 65535.0 + 0.5`. The index must be built in f32: doing the
    # multiply in f16 makes the literal 65535.0 round to f16 infinity, so every
    # sample lands in the top bin and psmMin/psmMax collapse to 1.0. With the
    # f32 index the f16 result matches f32.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.PlaneMinMax(minthr=0.1, maxthr=0.1, planes=[0])
    out32 = f32.vszip.PlaneMinMax(minthr=0.1, maxthr=0.1, planes=[0])
    assert_prop_parity(out16, out32, ["psmMin", "psmMax"], tol=1e-3)


@pytest.mark.parametrize("f16_fmt", [vs.GRAYH, vs.YUV420PH, vs.RGBH])
def test_f16_parity_planeminmax_diff(make_clip, f16_fmt):
    # psmDiff path: clipb (a real BoxBlur distortion) is computed independently
    # per precision, so the blur output and the |src-ref| accumulation diverge
    # at genuine f16 output precision. tol=1e-3 reflects that, not a logic bug.
    f16, f32 = pair(make_clip, f16_fmt)
    blur16 = f16.vszip.BoxBlur(hradius=1, vradius=1, planes=[0])
    blur32 = f32.vszip.BoxBlur(hradius=1, vradius=1, planes=[0])
    out16 = f16.vszip.PlaneMinMax(clipb=blur16, planes=[0])
    out32 = f32.vszip.PlaneMinMax(clipb=blur32, planes=[0])
    assert_prop_parity(out16, out32, ["psmDiff"], tol=1e-3)


# --- PlaneAverage -----------------------------------------------------------


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.YUV420PH, vs.RGBH],
    ids=["grayh", "yuv420ph", "rgbh"],
)
def test_f16_parity_planeaverage(make_clip, f16_fmt):
    # exclude= is REQUIRED and must be non-empty. exclude=[1] excludes the
    # peak (white, 1.0) pixels: the int 1 widens to float 1.0 in both paths,
    # but it is compared against the f16-stored value vs the f32-widened value,
    # so a divergent exclude count would shift the average and be exposed here.
    #
    # The f32 clip is an exact (byte-identical) widening of the f16 clip via
    # Point resize, so both averages sum the same numeric values in f64; any
    # difference is the filter's f16 read/compare path, not input quantization.
    #
    # Default planes (single plane) keeps psmAvg a scalar so assert_prop_parity
    # can compare it directly.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.PlaneAverage(exclude=[1])
    out32 = f32.vszip.PlaneAverage(exclude=[1])
    # psmAvg is a normalized 0..1 average; ~1e-3 is about 2 ULP of f16 near 1.0.
    assert_prop_parity(out16, out32, ["psmAvg"], tol=1e-3)


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.YUV420PH, vs.RGBH],
    ids=["yuv420ph", "rgbh"],
)
def test_f16_parity_planeaverage_multiplane(make_clip, f16_fmt):
    # Multi-plane output: psmAvg becomes a per-plane list. Compare element-wise
    # so divergence on any plane (e.g. chroma on the subsampled YUV layout) is
    # exposed, not averaged away.
    f16, f32 = pair(make_clip, f16_fmt)
    out16 = f16.vszip.PlaneAverage(exclude=[1], planes=[0, 1, 2])
    out32 = f32.vszip.PlaneAverage(exclude=[1], planes=[0, 1, 2])
    a16 = props(out16)["psmAvg"]
    a32 = props(out32)["psmAvg"]
    assert len(a16) == len(a32)
    for p, (v16, v32) in enumerate(zip(a16, a32)):
        assert abs(v16 - v32) <= 1e-3, f"plane {p}: {v16} vs {v32}"


@pytest.mark.parametrize(
    "f16_fmt",
    [vs.GRAYH, vs.RGBH],
    ids=["grayh", "rgbh"],
)
def test_f16_parity_planeaverage_diff(make_clip, f16_fmt):
    # clipb diff mode (psmDiff): the float branch sums abs(v-ref) in f64 with no
    # peak division. Use a real distortion (BoxBlur) of the reference so the diff
    # is nonzero and the f16-vs-f32 abs-diff accumulation is actually exercised.
    f16, f32 = pair(make_clip, f16_fmt)
    # std.BoxBlur has no f16 support; use vszip.BoxBlur and widen the f16 result
    # so clipb is byte-identical across runs (isolates PlaneAverage's f16 path).
    blur16 = f16.vszip.BoxBlur(hradius=3, vradius=3)
    blur32 = blur16.resize.Point(format=F16_TO_F32[f16_fmt])
    out16 = f16.vszip.PlaneAverage(exclude=[1], clipb=blur16)
    out32 = f32.vszip.PlaneAverage(exclude=[1], clipb=blur32)
    assert_prop_parity(out16, out32, ["psmAvg", "psmDiff"], tol=1e-3)


