name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Install VapourSynth
      shell: bash
      run: pip install VapourSynth

    - uses: mlugg/setup-zig@v2
      with:
        version: 0.16.0
        use-cache: false

    - name: build plugin
      run: zig build -Doptimize=Debug -Dcpu=x86_64_v3

    - name: Run test
      run: cd ./test/ && ./test_all.sh

  Windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install VapourSynth
      run: pip install VapourSynth

    - uses: mlugg/setup-zig@v2
      with:
        version: 0.16.0
        use-cache: false

    - name: build plugin
      run: zig build -Doptimize=Debug -Dcpu=x86_64_v3

    - name: Run test
      shell: pwsh
      run: test/test_all.ps1
